### PR TITLE
auto assign source IDs

### LINKED ISSUE #236: Crash on using clusterProperties due to adding duplicate source
While trying out how the clusterProperties work to properly document it, I noticed that it just crashes if one attempts to use it.

When I add in `ClusterPointsDemo` 

```kt
clusterProperties = mapOf("range" to GeoJsonOptions.ClusterProperty("+", feature.get("current_range_meters")))
```

(and `"current_range_meters" to (bike["current_range_meters"] ?: JsonNull),` in `readGbfsData` to actually have that data in the geojson)

the Android app will just crash in native code.

Of course, MapLibre should not crash, but maybe it crashes because the API is not used in the expected manner?

### PR DESCRIPTION
**Pull request by sargunv**
## Description

Fixes #236 and similar crashes when recreating sources by auto generating source IDs, which ensures we never have an ID conflict and we can remove sources after adding their replacements.

## Test plan

Re-enabled the cluster property demo, and also testing toggling demo visibility (which used to crash)

## Checklist

**To your knowledge, are you making any breaking changes?**

Yes, the `id` param is no longer provided to the `remember*Source` functions.

### CODE REVIEW

File: demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt [hunk 1]
```diff
@@ -70,25 +72,21 @@ object ClusteredPointsDemo : Demo {
...
-          //   ),
+          clusterProperties =
+            mapOf(
+              "total_range" to
+                GeoJsonOptions.ClusterPropertyAggregator(
+                  mapper = feature["current_range_meters"].convertToNumber(),
+                  reducer =
+                    feature.accumulated().asNumber() + feature["total_range"].convertToNumber(),
+                )
+            ),
```
Comment (sargunv) [inline demo-app/src/commonMain/kotlin/dev/sargunv/maplibrecompose/demoapp/demos/ClusteredPointsDemo.kt:89]: I want to tweak this cluster property to maybe sum up the different _types_ of vehicles and show the sums in the cluster somehow. Will leave that for #461.

For now, it's enough that this no longer crashes.
